using System;

public enum MixPanelEvents
{
	EnterGame = 1,
	ExitGame = 2,
	LevelUp = 3,
	EnterBase = 4,
	ExitBase = 5,
	GalaxyJump = 6,
	HyperJump = 7,
	UltraGalaxyJump = 8,
	CurrencyExchange = 9,
	StartQuest = 10,
	FailQuest = 11,
	CancelQuest = 12,
	CollectReward = 13,
	CollectDailyQuestReward = 14,
	TransformerSpin = 15,
	BuyShip = 16,
	OpenMenu = 17,
	PurchaseNeuronModules = 18,
	PurchaseBooster = 19,
	SkillCast = 20,
	SkillReroll = 21,
	SkillPoints = 22,
	SignForPvP = 23,
	StartPvPgame = 24,
	EndPvPgame = 25,
	CreateGuild = 26,
	JoinGuild = 27,
	AddToFriends = 28,
	AddToBlacklist = 29,
	OpenLoginSceneMobile = 30,
	RegisterMobile = 31,
	StartTutorialMobile = 32,
	TutorialStepMobile = 33,
	FinishTutorialMobile = 34,
	PurchaseNovaMobile = 35,
	StartQuestMobile = 36,
	CompleteQuestMobile = 37,
	SkipQuestMobile = 38,
	InstallGameMobile = 39
}